### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by klev-sm** [klev-sm/akiaxa#2]
- [ ] Criar ReadMe.
- [ ] Editar background image da página inicial.
- [ ] Criar Layout Responsivo para a página inicial.
- [ ] Editar conteúdo do footer da página inicial.
